name: scraper_cli
description: A CLI program for scraping the arrahma website for content.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  simple_json_mapper: ^0.2.2
  scraper:
    path: ../scraper

dev_dependencies:
  build_runner: ^1.10.0
  simple_json: ^0.2.6
