name: scraper
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  html: ^0.15.4
  xml: ^6.5.0
  http: ^1.2.2
  recase: ^4.1.0
  arrahma_shared:
    path: ../shared
  html2md: ^1.3.2

dev_dependencies:
  pedantic: ^1.11.1
  test: ^1.25.8
