name: scraper
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.10.4 <3.0.0"

dependencies:
  html: ^0.14.0+2
  xml: ^4.5.1
  http: ^0.12.2
  recase: ^3.0.1
  arrahma_shared:
    path: ../shared
  html2md: ^0.5.1

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
