name: arrahma_shared
description: Shared shared for the arrahma app.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  dart_json_mapper: ^2.2.13
  intl: ^0.19.0
  logging: ^1.2.0

#  path: ^1.6.0

dev_dependencies:
  pedantic: ^1.11.1
  test: ^1.25.8
  build_runner: ^2.4.12
