name: arrahma_shared
description: Shared shared for the arrahma app.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.10.4 <3.0.0"

dependencies:
  simple_json_mapper: ^1.1.3
  intl: ^0.16.1
  logging: ^0.11.4

#  path: ^1.6.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
  build_runner: ^1.10.0
  simple_json: ^1.2.2
