googleApiKey: AIzaSyB9NmUBYl4LcIxBqd3xvEZWGKgla1SmycI
youtubeChannelId: UCp5ml9LRjRDoYpt6allcR7w
facebookChannelId: arrahmah.islamic.institute
mixlrChannelId: '78663'
errorEmailRecipient: tehtech1337+arrahmah@gmail.com
senderEmail: tehtech1337@gmail.com
senderEmailPassword: utomitvsgcnztmgq
# mixlrChannelUserName: arrahma-live