name: arrahma_web_api
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
 aqueduct: ^3.3.0+1
 arrahma_models:
  path: ../models
 scraper_service:
  path: ../scraper_service

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0