name: arrahma_web_api
publish_to: none
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  conduit: ^5.1.3
  conduit_core: ^5.1.3
  dart_json_mapper: ^2.2.13
  uuid: ^4.4.2
  scraper_service:
    path: ../scraper_service
  arrahma_shared: 
    path: ../shared
  http: ^1.2.2

dev_dependencies:
  pedantic: ^1.11.1
  test: ^1.25.8
