name: scraper_service
description: A service program for accessing and scraping the arrahma website for content.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  dart_json_mapper: ^2.2.13
  crypto: ^3.0.3
  mailer: ^6.1.2
  scraper:
    path: ../scraper
  arrahma_shared:
    path: ../shared
